#!/bin/bash
# //====================================================
# //	System Request:Debian 9+/Ubuntu 18.04+/20+
# //	Develovers >   LT
# //	email > scvip293@gmail.com
# //    telegram > https://t.me/LunaticTunnel
# //    whatsapp > 082240074362
# //====================================================
# // LUNATIC TUNNELING
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
IP=$(curl -s ipv4.icanhazip.com)
HOST="$(cat /etc/xray/domain)"
DATEVPS=$(date +"%d-%B-%Y")
ISPVPS=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
GREEN="\e[92;1m"
BLUE="\033[36m"
RED='\033[0;31m'
NC='\033[0m'
function BACKUPVPS() {
    mkdir -p /root/backup
    cp -r /etc/xray/config.json backup/ >/dev/null 2>&1
    cp -r /etc/xray/*.log backup/ >/dev/null 2>&1
    cp /etc/passwd backup/
    cp /etc/group backup/
    cp /etc/shadow backup/
    cp /etc/gshadow backup/
    cp -r /var/www/html backup/html
    cp -r /etc/ssh/.ssh.db backup/ssh.db
    cp -r /etc/vmess/.vmess.db backup/vmess.db
    cp -r /etc/vless/.vless.db backup/vless.db
    cp -r /etc/trojan/.trojan.db backup/trojan.db
    cp -r /etc/shadowsocks/.shadowsocks.db backup/shadowsocks.db
    zip -r KYT-${DATEVPS}.zip backup >/dev/null 2>&1
    rclone copy FT-${DATEVPS}.zip dr:BACKUPVPS/
    url=$(rclone link dr:BACKUPVPS/FT-${DATEVPS}.zip)
    id=($(echo $url | grep '^https' | cut -d'=' -f2))
    LINKBACKUP="https://drive.google.com/u/4/uc?id=${id}&export=download"
    rm -rf backup
    rm -rf KYT-${DATEVPS}.zip
    echo "
_______________________________________
SUCCESSFULL BACKUP YOUR VPS
Please Save The Following Data
_______________________________________
YOUR VPS IP : $IP
DOMAIN      : $HOST
DATE        : $DATEVPS
ISP         : $ISPVPS
LOCATION    : $CITY
LINK BACKUP : $LINKBACKUP
_______________________________________

Report bugs   : https://t.me/LunaticTunnel
LunaticTunnel Project
    " | mail -s "LunaticTunneling Backup"  $EMAIL
    echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━━━◇"
    echo -e "SUCCESSFULL BACKUP YOUR VPS"
    echo -e "Please Save The Following Data"
    echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━━━◇"
    echo -e "Your VPS IP : $IP"
    echo -e "DOMAIN      : $HOST"
    echo -e "DATE        : $DATEVPS"
    echo -e "ISP         : $ISPVPS"
    echo -e "LOCATION    : $CITY"
    echo -e "LINK BACKUP : $LINKBACKUP"
    echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━━━◇"
    echo -e "Please Check your Email backup file"

}
BACKUPVPS
