#!/bin/bash
# //====================================================
# //	System Request:Debian 9+/Ubuntu 18.04+/20+
# //	Develovers >   LT
# //	email > scvip293@gmail.com
# //    telegram > https://t.me/LunaticTunnel
# //    whatsapp > 082240074362
# //====================================================
# // LUNATIC TUNNELING
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
IP=$(curl -s ipv4.icanhazip.com)
HOST="$(cat /etc/xray/domain)"
DATEVPS=$(date +"%d-%B-%Y")
ISPVPS=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
GREEN="\e[92;1m"
BLUE="\033[36m"
RED='\033[0;31m'
NC='\033[0m'
read -p "Plase Input Link : " DATAVPS
function RESTOREVPS() {
    wget -O backup.zip "$DATAVPS" >/dev/null 2>&1
    unzip *.zip >/dev/null 2>&1
    #    rm -f *.zip >/dev/null 2>&1
    cp /root/backup/passwd /etc/
    cp /root/backup/group /etc/
    cp /root/backup/shadow /etc/
    cp /root/backup/gshadow /etc/
    cp -r /root/backup/html /var/www/
    cp -r /root/backup/ssh.db /etc/ssh/.ssh.db
    cp -r /root/backup/vmess.db /etc/vmess/.vmess.db
    cp -r /root/backup/vless.db /etc/vless/.vless.db
    cp -r /root/backup/trojan.db /etc/trojan/.trojan.db
    cp -r /root/backup/shadowsocks.db /etc/shadowsocks/.shadowsocks.db
    cp -r /root/backup/*.json /etc/xray >/dev/null 2>&1
    cp -r /root/backup/*.log /etc/xray >/dev/null 2>&1
    cp /etc/openvpn/*.ovpn /var/www/html/
    cd
    systemctl restart xray >/dev/null 2>&1
    rm -rf backup.zip
    echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━━━◇"
    echo -e "SUCCESSFULL RESTORE YOUR VPS"
    echo -e "Please Save The Following Data"
    echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━━━◇"
    echo -e "Your VPS IP : $IP"
    echo -e "DOMAIN      : $HOST"
    echo -e "DATE        : $DATEVPS"
    echo -e "ISP         : $ISPVPS"
    echo -e "LOCATION    : $CITY"
    echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━━━◇"
    echo -e "Please Reboot Vps"
}
RESTOREVPS
