#!/bin/bash
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
# Color
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'


BlueCyan="\033[5;36m"
WhiteBe="\033[5;37m"
yellow="\033[0;33m"
ungu="\033[0;35m"
Xark="\033[0m"
BlueCyan="\033[5;36m"
WhiteBe="\033[5;37m"
GreenBe="\033[5;32m"
# . Liner 
function baris_panjang() {
  echo -e "${BlueCyan} ——————————————————————————————————— ${Xark} "
}

function Lunatic_Banner() {
clear
baris_panjang
echo -e "${ungu}           ARISCTUNNEL V3       ${Xark} "
baris_panjang
}



green() { echo -e "\\033[32;1m${*}\\033[0m"; }
red() { echo -e "\\033[31;1m${*}\\033[0m"; }
clear


NUMBER_OF_CLIENTS=$(grep -c -E "^#! " "/etc/xray/config.json")
	if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        baris_panjang
		echo "Name $user is Wrong !!"
		echo ""
		echo -e "${yellow} Nama $user Ini Tidak ada- ${Xark} "
		echo -e "${yellow} Mohon Pastikan Username Ada ${Xark}"
        baris_panjang
		read -p "Back To Menu"
        menu
	fi

	clear
	baris_panjang
    echo -e "${yellow}          Delete Akun Trojan           ${Xark} "
    
    baris_panjang
    echo -e "${yellow}  User       Expired   ${Xark}" 
	baris_panjang
	
	grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | column -t | sort | uniq
    echo ""
    
    baris_panjang
	read -rp " Input UserName : " user
    baris_panjang
    
    if [ -z $user ]; then
    m-tro
    else
    exp=$(grep -wE "^#! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    sed -i "/^#! $user $exp/,/^},{/d" /etc/xray/config.json
    sed -i "/### $user $exp/,/^},{/d" /etc/trojan/.trojan.db
    rm -rf /etc/trojan/$user
    rm -rf /etc/kyt/limit/trojan/ip/$user
    systemctl restart xray > /dev/null 2>&1
    echo ""
    echo ""
    Lunatic_Banner
    baris_panjang
    echo -e "${GreenBe} Succesfuly${Xark} "
    baris_panjang
    echo -e "${yellow} Username ${GreenBe}$user ${Xark} "
    echo -e "${yellow} Sukses Di Hapus ${Xark} "
    baris_panjang
    fi