#!/bin/bash

yellow="\033[0;33m"
ungu="\033[0;35m"
Red="\033[91;1m"
Xark="\033[0m"
BlueCyan="\033[5;36m"
WhiteBe="\033[5;37m"
GreenBe="\033[5;32m"
YellowBe="\033[5;33m"
BlueBe="\033[5;34m"
# . Liner 
function baris_panjang() {
  echo -e "${BlueCyan} ——————————————————————————————————— ${Xark} "
}

function Lunatic_Banner() {
clear
baris_panjang
echo -e "${ungu}           ARISCTUNNEL V3       ${Xark} "
baris_panjang
}

function Sc_Credit(){
sleep 1
baris_panjang
echo -e "${ungu}  Terimakasih Telah Menggunakan ${Xark}"
echo -e "${ungu}          Script Credit ${Xark}"
echo -e "${ungu}          ARISCTUNNEL V3  ${Xark}"
baris_panjang
exit 1
}

duration=6
frames=("██10%" "█████35%" "█████████65%" "█████████████80%" "█████████████████████90%" "█████████████████████████100%")

# Menghitung jumlah frame
num_frames=${#frames[@]}

# Menghitung jumlah iterasi
num_iterations=$((duration))

# Fungsi untuk menampilkan animasi loading berwarna

Loading_Animasi() {
    for ((i = 0; i < num_iterations; i++)); do
        clear
        index=$((i % num_frames))
        color_code=$((31 + i % 7))
echo ""
echo ""
echo ""
echo -e "\e[1;${color_code}m ${frames[$index]}\e[0m"
sleep 0.5
    done
}

# Menjalankan animasi loading

# Menampilkan pesan setelah animasi selesai
function Loading_Succes() {
clear
echo -e  "\033[5;32mSucces\033[0m"
sleep 2
clear
}


function Daftar_User_Vless() {
grep -E "^#& " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | column -t | sort | uniq

}

clear
Lunatic_Banner
baris_panjang
Daftar_User_Vless
baris_panjang
echo ""
read -p "Input Username  : " user
baris_panjang
limit_file="/etc/kyt/limit/vless/ip/${user}"

# Validasi apakah file batasan IP sudah ada
if [ -e "$limit_file" ]; then
  current_iplimit=$(cat "$limit_file")
  echo "Limit ip is User $user: $current_iplimit"
baris_panjang
echo ""
read -p "Input New ip    : " new_iplimit
baris_panjang
echo -e ""
Loading_Animasi
Loading_Succes

  # Validasi jika masukan kosong
  if [ -z "$new_iplimit" ]; then
Lunatic_Banner
baris_panjang
    echo -e "${Red} GAGAL !! ${Xark} "
baris_panjang
Sc_Credit
  else
    echo "$new_iplimit" > "$limit_file"
    
    Lunatic_Banner
    baris_panjang
    echo -e "${GreenBe} Succesfully ${Xark} "
    echo ""
    echo ""
    echo -e "${yellow} New Ip    : $new_iplimit GB ${Xark} "
    echo -e "${yellow} Username  : $user ${Xark} "
    baris_panjang
    Sc_Credit
    
  fi
else
  echo "File batasan IP tidak ditemukan untuk pengguna $user."
fi
