#!/bin/bash

yellow="\033[0;33m"
ungu="\033[0;35m"
Red="\033[91;1m"
Xark="\033[0m"
BlueCyan="\033[5;36m"
WhiteBe="\033[5;37m"
GreenBe="\033[5;32m"
YellowBe="\033[5;33m"
BlueBe="\033[5;34m"
Cyan="\033[96;1m"
KUNING="\033[93;1m"

# . Liner 
function baris_panjang() {
  echo -e "${BlueCyan} ——————————————————————————————————— ${Xark} "
}

function Lunatic_Banner() {
clear
baris_panjang
echo -e "${ungu}           ARISCTUNNEL V3       ${Xark} "
baris_panjang
}

function Sc_Credit(){
sleep 1
baris_panjang
echo -e "${ungu}  Terimakasih Telah Menggunakan ${Xark}"
echo -e "${ungu}          Script Credit ${Xark}"
echo -e "${ungu}          ARISCTUNNEL V3  ${Xark}"
baris_panjang
exit 1
}

duration=6
frames=("██10%" "█████35%" "█████████65%" "█████████████80%" "█████████████████████90%" "█████████████████████████100%")

# Menghitung jumlah frame
num_frames=${#frames[@]}

# Menghitung jumlah iterasi
num_iterations=$((duration))

# Fungsi untuk menampilkan animasi loading berwarna

Loading_Animasi() {
    for ((i = 0; i < num_iterations; i++)); do
        clear
        index=$((i % num_frames))
        color_code=$((31 + i % 7))
echo ""
echo ""
echo ""
echo -e "\e[1;${color_code}m ${frames[$index]}\e[0m"
sleep 0.5
    done
}

# Menjalankan animasi loading

# Menampilkan pesan setelah animasi selesai
function Loading_Succes() {
clear
echo -e  "\033[5;32mSucces\033[0m"
sleep 1
clear
}


Lunatic_Banner
baris_panjang
    echo -e "${yellow}  Username   exp   ${Xark}" 
baris_panjang
echo ""	
	grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | column -t | sort | uniq
echo ""
baris_panjang
echo ""
read -p "Input Username :  " user
limit_file="/etc/kyt/limit/trojan/ip/${user}"

# Validasi apakah file batasan IP sudah ada
if [ -e "$limit_file" ]; then
  current_iplimit=$(cat "$limit_file")
baris_panjang
  echo -e "${Cyan} BEFORE ${Xark}"
  echo ""
  echo -e "${yellow} Username   : $user ${Xark} "
  echo -e "${yellow} Ip Limit   :  $current_iplimit ${Xark} "
baris_panjang
echo ""
echo ""
       read -p " Input New  Ip  :  " new_iplimit

  # Validasi jika masukan kosong
  if [ -z "$new_iplimit" ]; then


Lunatic_Banner
baris_panjang
    echo ""
    echo -e "${Red} Sorry ${Xarrk} "
    echo -e ""
    echo -e " Batasan ip Tidak di Temukan "
    echo -e " untuk Username : ${Green}$user ${Xark}"
    echo ""
    baris_panjang
    Sc_Credit
    
    
  else
echo "$new_iplimit" > "$limit_file"
Lunatic_Banner
    echo -e "${GreenBe} Succesfully ${Xark} "
echo ""
    echo -e "${KUNING} New Ip     : $new_iplimit ${Xark} "
    echo -e "${KUNING} Username   : $user ${Xark} "
echo ""
baris_panjang
Sc_Credit


  fi
else
Lunatic_Banner
baris_panjag
echo ""
  echo -e "${Cyan} File IP tidak ditemukan untuk : $user ${Xark} "
echo ""
baris_panjang
Sc_Credit
fi
