#!/bin/bash

yellow="\033[0;33m"
ungu="\033[0;35m"
Red="\033[91;1m"
YELLOW="\033[93;1m"
Xark="\033[0m"
BlueCyan="\033[5;36m"
Cyan="\033[96;1m"
Purple="\033[95;1m"
Green="\033[92;1m"
WhiteBe="\033[5;37m"
GreenBe="\033[5;32m"
YellowBe="\033[5;33m"
BlueBe="\033[5;34m"
# . Liner 
function baris_panjang() {
  echo -e "${BlueCyan} ——————————————————————————————————— ${Xark} "
}

function Lunatic_Banner() {
clear
baris_panjang
echo -e "${ungu}           ARISCTUNNEL V3       ${Xark} "
baris_panjang
}

function Sc_Credit(){
sleep 1
baris_panjang
echo -e "${ungu}  Terimakasih Telah Menggunakan ${Xark}"
echo -e "${ungu}          Script Credit ${Xark}"
echo -e "${ungu}          ARISCTUNNEL V3  ${Xark}"
baris_panjang
exit 1
}

duration=6
frames=("██10%" "█████35%" "█████████65%" "█████████████80%" "█████████████████████90%" "█████████████████████████100%")

# Menghitung jumlah frame
num_frames=${#frames[@]}

# Menghitung jumlah iterasi
num_iterations=$((duration))

# Fungsi untuk menampilkan animasi loading berwarna

Loading_Animasi() {
    for ((i = 0; i < num_iterations; i++)); do
        clear
        index=$((i % num_frames))
        color_code=$((31 + i % 7))
echo ""
echo ""
echo ""
echo -e "\e[1;${color_code}m ${frames[$index]}\e[0m"
sleep 0.5
    done
}

# Menjalankan animasi loading

# Menampilkan pesan setelah animasi selesai
function Loading_Succes() {
clear
echo -e  "\033[5;32mSucces\033[0m"
sleep 1
clear
}
clear
echo -e "\033[5;36m┌──────────────────────────────────────────┐\033[0m"
echo "   USERNAME       EXP DATE         STATUS"
echo -e "\033[5;36m└──────────────────────────────────────────┘\033[0m"
echo -e "\033[5;36m┌──────────────────────────────────────────┐\033[0m"
while read expired
do
AKUN="$(echo $expired | cut -d: -f1)"
ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
status="$(passwd -S $AKUN | awk '{print $2}' )"
if [[ $ID -ge 1000 ]]; then
if [[ "$status" = "L" ]]; then
 printf "%-17s %2s %-17s %2s \n" "  $AKUN" "$exp   " "LOCKED${NORMAL}"
else
 printf "%-17s %2s %-17s %2s \n" "  $AKUN" "$exp   " "UNLOCKED${NORMAL}"
fi
fi
done < /etc/passwd
JUMLAH="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
echo -e "\033[5;36m└──────────────────────────────────────────┘\033[0m"
echo -e "\033[5;36m┌──────────────────────────────────────────┐\033[0m"
echo "   Account number: $JUMLAH   user"
echo -e "\033[5;36m└──────────────────────────────────────────┘\033[0m"
echo -e ""
read -p "input username: " user
limit_file="/etc/kyt/limit/ssh/ip/$user"

# Validasi apakah file batasan IP sudah ada
if [ -e "$limit_file" ]; then
  current_iplimit=$(cat "$limit_file")
  Lunatic_Banner
  baris_panjang
  echo -e "${Cyan} Before ${Xark} "
  echo -e ""
  echo -e "${yellow} Username   : $user ${Xark} "
  echo -e "${yellow} Ip Limit   : $current_iplimit ${Xark}"
  echo -e ""
  baris_panjang
  echo -e ""
  read -p "Input New Ip   : " new_iplimit

Loading_Animasi
Loading_Succes


  # Validasi jika masukan kosong
  if [ -z "$new_iplimit" ]; then
    echo -e "${White} Invallid !! "
  else
    echo "$new_iplimit" > "$limit_file"
    Lunatic_Banner
    baris_panjang
    echo -e "${GreenBe} Succesfully ${Xark} "
    echo -e ""
    echo -e "${Cyan} After  ${Xark} "
    echo -e ""
    echo -e "${yellow} New Ip   : $new_iplimit ${Xark} "
    echo -e "${yellow} Username : $user ${Xark} "
    echo -e ""
    baris_panjang
    Sc_Credit
    
  fi
else

Lunatic_Banner
baris_panjang
  echo -e "${Red} Sorry ${Xark} "
echo ""
  echo -e "${YELLOW} Username   : $user "
  echo -e "${YELLOW} IP LIMIT   : invallid !! ${Xark} "
echo ""
baris_panjang
Sc_Credit

fi
