#!/bin/bash

BlueCyan='\e[5;36m'
Xark='\e[0m'
ungu='\033[0;35m'
yellow='\e[33m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
BlueCyan='\e[5;36m'
Xark='\e[0m'
clear

function baris_panjang() {
  echo -e "${BlueCyan} ——————————————————————————— ${Xark} "
}

# . 1
function Create_Vless() {
  add-vle
}

# . 2
function Create_Trial() {
  trial-vle
}

# . 4
function List_Member() {
  member-vle
}

# . 3
function Delete_Exp() {
  del-vle
}

function Changes_Limit() {
  limit-Vless
}

# . 5 
function Renew_Vless() {
  renew-vle
}

# . 6 
function Check_Account() {
  user-vle
}

# . 7 
function Change_Ip_Limit() {
  ganti-ip-vless
}

# . 8 
function Change_Vless_Quota() {
  change-vless-qouta
}

function Banner() {
  baris_panjang
  echo -e "${ungu}           Vless      ${Xark} "
  baris_panjang
}

function Menu_Features() {
  baris_panjang
  echo -e "${ungu}"
  echo " 1. Create Vless   "
  echo " 2. Trial Vless "
  echo " 3. Delete Vless    "
  echo " 4. List Member "
  echo " 5. Renew Account "
  echo " 6. Change Limit IP "
  echo " 7. Change Vless Quota "
  echo -e "${Xark}"
  echo -e "${yellow} x. Exit ${Xark}"
  baris_panjang
}

Banner
Menu_Features
read -p "Select [1/7 or x] :  " Ltt
case $Ltt in
1) clear ; Create_Vless ;;
2) clear ; Create_Trial ;;
3) clear ; Delete_Vless ;;
4) clear ; List_Member ;;
5) clear ; Renew_Account ;;
6) clear ; Change_Ip_Limit ;;
7) clear ; Change_Vless_Quota ;;
*) exit ;;
esac
