#!/bin/bash
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
green() { echo -e "\\033[32;1m${*}\\033[0m"; }
red() { echo -e "\\033[31;1m${*}\\033[0m"; }
clear

yellow="\033[0;33m"
ungu="\033[0;35m"
Red="\033[91;1m"
Xark="\033[0m"
BlueCyan="\033[5;36m"
WhiteBe="\033[5;37m"
GreenBe="\033[5;32m"
YellowBe="\033[5;33m"
BlueBe="\033[5;34m"
# . Liner 
function baris_panjang() {
  echo -e "${BlueCyan} ——————————————————————————————————— ${Xark} "
}

function Lunatic_Banner() {
clear
baris_panjang
echo -e "${ungu}           ARISCTUNNEL V3       ${Xark} "
baris_panjang
}

function Sc_Credit(){
sleep 1
baris_panjang
echo -e "${ungu}  Terimakasih Telah Menggunakan ${Xark}"
echo -e "${ungu}          Script Credit ${Xark}"
echo -e "${ungu}          ARISCTUNNEL V3  ${Xark}"
baris_panjang
exit 1
}

duration=6
frames=("██10%" "█████35%" "█████████65%" "█████████████80%" "█████████████████████90%" "█████████████████████████100%")

# Menghitung jumlah frame
num_frames=${#frames[@]}

# Menghitung jumlah iterasi
num_iterations=$((duration))

# Fungsi untuk menampilkan animasi loading berwarna

Loading_Animasi() {
    for ((i = 0; i < num_iterations; i++)); do
        clear
        index=$((i % num_frames))
        color_code=$((31 + i % 7))
echo ""
echo ""
echo ""
echo -e "\e[1;${color_code}m ${frames[$index]}\e[0m"
sleep 0.5
    done
}

# Menjalankan animasi loading

# Menampilkan pesan setelah animasi selesai
function Loading_Succes() {
clear
echo -e  "\033[5;32mSucces\033[0m"
sleep 2
clear
}


function Daftar_User_Vless() {
grep -E "^#& " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | column -t | sort | uniq

}



NUMBER_OF_CLIENTS=$(grep -c -E "^#& " "/etc/xray/config.json")
	if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
		clear
Lunatic_Banner
        baris_panjang
        echo -e "${yellow}       RENEW VLESS  ${Xark} "
        baris_panjang
		echo ""
		echo -e "${Red} Nama Is Wrong !!! ${Xark} "
		echo ""
		baris_panjang
Sc_Credit
        echo ""
        read -n 1 -s -r -p "Press any key to back on menu"
        menu
	fi

	clear
        baris_panjang
        echo -e "${yellow}       RENEW VLESS  ${Xark} "
        baris_panjang
		echo ""
  	grep -E "^#& " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | column -t | sort | uniq
    echo ""
    red "tap enter to go back"
        baris_panjang
    echo ""
	read -rp "Input Username   : " user
baris_panjang
    if [ -z $user ]; then
    menu
    else
    rm -f /etc/kyt/limit/vless/ip/${user}
    rm -f /etc/vless/$user
    read -p "Expired (days)   : " masaaktif
baris_panjang
    read -p "Limit User (GB)  : " Quota
baris_panjang
    read -p "Limit User (IP)  : " iplim
baris_panjang
echo ""

Loading_Animasi
Loading_Succes

    exp=$(grep -wE "^#& $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    mkdir -p /etc/kyt/limit/vless/ip
echo ${iplim} >> /etc/kyt/limit/vless/ip/${user}
if [ ! -e /etc/vless/ ]; then
  mkdir -p /etc/vless/
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/vless/${user}
fi
    now=$(date +%Y-%m-%d)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(( (d1 - d2) / 86400 ))
    exp3=$(($exp2 + $masaaktif))
    exp4=`date -d "$exp3 days" +"%Y-%m-%d"`
    sed -i "/#& $user/c\#& $user $exp4" /etc/xray/config.json
    sed -i "/#& $user/c\#& $user $exp4" /root/akun/vless/.vless.conf
    systemctl restart xray > /dev/null 2>&1
    clear

Lunatic_Banner
baris_panjang
    echo -e "${GreenBe} Successfully ${Xark} "
    echo ""
    echo -e "${yellow}"
    echo " Client Name   : $user"
    echo " Expired On    : $exp4"
    echo " User Quota    : $Quota"
    echo " User Limit IP : $iplim"
    echo -e "${Xark}"
    echo ""
baris_panjang
Sc_Credit
    echo ""
    read -n 1 -s -r -p "Press any key to back on menu"
    menu
    fi
